kind: Secret
apiVersion: v1
metadata:
  name: {{ include "kube-db-shipper.fullname" . }}-dump
stringData:
  {{- if eq .Values.dump.type "postgresql" }}
  {{- with .Values.dump.postgresql }}
  PGPASSWORD: {{ .password }}
  PGUSER: {{ .username }}
  {{- end }}
  {{- end }}
