{{- range .Values.shippers }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "kube-db-shipper.fullname" $ }}-{{ .name }}
stringData:
  {{- if eq .type "s3" }}
  AWS_ACCESS_KEY_ID: {{ .s3.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .s3.secretKey | quote }}
  AWS_BUCKET: {{ .s3.bucket | quote }}
  AWS_ENDPOINT_URL: {{ .s3.endpointUrl | quote }}
  {{- end }}
{{- end }}
---